### ISSUE TITLE
google-beta provider availibity

### ISSUE THREAD

**Issue by mprince** [starhawking/python-terrascript#107]
Hello guys! To access beta features in GCP using the terraform GCP providers, it has now been separated into 2 distinct providers as shown in the [documentation] (https://www.terraform.io/docs/providers/google/guides/provider_versions.html#google-beta)as of version 1.19.0 of the provider. I don't see that provider available in the library in the latest version 0.8.0. If it's not available when is it being planned on being added?

**Comment by ilons** [comment]
I can have a look at adding this after I have cleaned up the generator some.

Or if you would like to have a try at it: tools/makecode.py is the script responsible to add new providers, through the defined ones in tools/providers.yml.

**Comment by ilons** [comment]
This should now be fixed in develop, would you mind going for a spin with it @mprince?

**Comment by mprince** [comment]
Sorry for late reply but I got drifted on this. If this will be included in release 0.9.0 I could wait for it at this point. Thanks for answering @ilons

**Comment by ilons** [comment]
Included in https://github.com/mjuenema/python-terrascript/releases/tag/0.9.0
