### ISSUE TITLE
Looking for new maintainer.

### ISSUE THREAD

**Issue by mjuenema** [starhawking/python-terrascript#110]
As many of you will have already noticed, unfortunately I don't have sufficient time to properly maintain python-terrascript anymore.

What was intended to be a just small experiment turned into my most popular Github project with more than 250 stars. In turn this means that at least 250 other people have a certain level of expectation towards me actually mainatining the project to a certain level of quality. I am simply not able to meet this expectation anymore and don't want to pretend that I could. I am happy to pass the baton on to someone else who's willing to jump in.

**Comment by ilons** [comment]
Would you be wiling to stay as maintainer if you get one or more persons who step in to help?

Since the reasons you mention for wanting to find the project a new maintainer, would probably also be true for the next maintainer.

I could help maintaining the project to some extent since I plan to actively use it, but feel it would be good to have you onboard going forward, if nothing else at least as a mentor to share your intentions with certain implementation details.

**Comment by mjuenema** [comment]
Hi Ilon, that's a possible approach. I am going to add you as a maintainer.

**Comment by mjuenema** [comment]
There are already two other people who are collaborators (the official term), @nielsonsantana and @Spikeophant, although neither have used that level access yet. From memory, both have contributed pull requests previously.

@ilons, feel free to take over as much as you like. Judging from your recent pull requests you seem to have a good understanding of the project. I mentioned that I don't have enough time for maintaining the project. That's not necessarily the full picture. The key issue is that I don't actually use Python-Terrascript *at all* these days and practically have to re-learn it myself over and over again. I am happy to slip more into a mentoring role.

**Comment by ilons** [comment]
I understand, and have also got that impression already from reading small notes in the documentation for example (where you ask for real world cases).

I'll try to give it some love, time will tell how it goes.
Please just tell me if you have opinions on any changes I do.

In the meantime:
**If anyone else feel like they would like to contribute to the continued development of the project, please answer here.**

**Comment by mjuenema** [comment]
Hi @ilons, do you want to remove the "Looking for new maintainer" section in ``README.rst`` or shall I do it?

**Comment by ilons** [comment]
> Hi @ilons, do you want to remove the "Looking for new maintainer" section in `README.rst` or shall I do it?

I can update it, I have an idea of how to put it.

**Comment by ilons** [comment]
README are updated, closing this

**Comment by nielsonsantana** [comment]
Hi @ilons and @mjuenema!! 
Thanks @mjuenema for all your work around the last 2 years and the recent rewrite of terrascript. Was nice contribute with this interesting project.
Thanks @ilons to continue the work and as soon as possible I would contribute again. Currently I'm not actively using the project but I hope use it again.
