### ISSUE TITLE
Remove support for Python 3.5

### ISSUE THREAD

**Issue by ilons** [starhawking/python-terrascript#121]
As 3.5 approaches its end-of-life date (2020-09-13)[https://devguide.python.org/#status-of-python-branches], we should also drop support for it and stop building it.
This would allow for us to pick up 3.9 being released on (2020-10-04)[https://devguide.python.org/#status-of-python-branches] and in the long run make for less workarounds for legacy.

**Comment by mjuenema** [comment]
That's fair enough, given that only a small number of downloads from PyPi are for Python 3.5.

Version | Downloads
-- | --
3.4 | 4 |  
2.7 | 44 |  
3.5 | 409 |  
3.8 | 534 |  
3.6 | 4352 |  
null | 5204 |  
3.7 | 6732 |  

https://console.cloud.google.com/bigquery
```
SELECT 
   REGEXP_EXTRACT(details.python, r'^\d*\.\d*') python
  , COUNT(*) downloads
FROM `the-psf.pypi.downloads2020*`
WHERE file.project='terrascript'
GROUP BY python
ORDER BY downloads
```

**Comment by hugovk** [comment]
Please see PR #124 to drop 3.5, and #125 to test on 3.9-dev to make sure tests are passing for the full 3.9.0 release.

**Comment by ilons** [comment]
Great work @hugovk, much appreciated help with the move to Python 3.9.
