### ISSUE TITLE
Fail builds on files modified by Black

### ISSUE THREAD

**Issue by ilons** [starhawking/python-terrascript#127]
In order to make it easier for contributor to keep a consistent code style, we should start fail builds for any files changed when running `make black` in the build.
This would ensure that code changes adhere to the code style dictated by Black.

**Comment by mjuenema** [comment]
I agree, but to ensure consistent outcomes Black must be pinned to a specific version.

**Comment by ilons** [comment]
> I agree, but to ensure consistent outcomes Black must be pinned to a specific version.

Ah yes, this is coming in as part of https://github.com/mjuenema/python-terrascript/pull/124

**Comment by mjuenema** [comment]
:+1:
