### ISSUE TITLE
Added null_resource Resource

### ISSUE THREAD

**Issue by jackluo923** [starhawking/python-terrascript#154]
Pull request: https://github.com/mjuenema/python-terrascript/pull/153
- Added [null_resource resource](https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource) updated documents according to the contributing guidelines.
- I did not include a test for such simple change. If a test is needed, let me know and I will create one.

**Comment by ilons** [comment]
Thank you for the contribution, I just merged this.
