### ISSUE TITLE
Support new AWS resource `aws_config_configuration_aggregator`

### ISSUE THREAD

**Issue by jbscare** [starhawking/python-terrascript#40]
terraform-provider-aws version 1.22.0 supports AWS Config Aggregators, with a new `aws_config_configuration_aggregator` resource (https://www.terraform.io/docs/providers/aws/r/config_configuration_aggregator.html), but Terrascript doesn't seem to know about it:
```
Traceback (most recent call last):
  File "./terrascript-iam.py", line 133, in <module>
    ts += terrascript.aws.r.config_configuration_aggregator\
AttributeError: module 'terrascript.aws.r' has no attribute 'config_configuration_aggregator'
```

**Comment by mjuenema** [comment]
I moved house last week and my computers are still in boxes. So please be a bit patient before I can address this issue. Thanks, Markus.

**Comment by nbommu1** [comment]
PR for this, https://github.com/mjuenema/python-terrascript/issues/40
