### ISSUE TITLE
Support new AWS resource `aws_kms_grant'

### ISSUE THREAD

**Issue by nbommu1** [starhawking/python-terrascript#47]
terraform-provider-aws version 1.22.0 supports aws_kms_grants (https://www.terraform.io/docs/providers/aws/r/kms_grant.html), but Terrascript doesn't seem to know about it:

Traceback (most recent call last):
  File "./terrascript-nonprod.py", line 84, in <module>
    ts += terrascript.aws.r.kms_grant\
AttributeError: module 'terrascript.aws.r' has no attribute 'kms_grant'

**Comment by nbommu1** [comment]
PR for this, https://github.com/mjuenema/python-terrascript/pull/49

**Comment by mjuenema** [comment]
This has been implemented in #51.
