### ISSUE TITLE
Please add matchbox provider support 

### ISSUE THREAD

**Issue by ghost** [starhawking/python-terrascript#55]
Please include  support for "matchbox provider " 
https://github.com/coreos/terraform-provider-matchbox

**Comment by mjuenema** [comment]
I am not familiar with Matchbox at all. Do you think you could implement it yourself and submit a pull request?

**Comment by mjuenema** [comment]
I am going to add this to release 0.8.0

**Comment by mjuenema** [comment]
Added: https://github.com/mjuenema/python-terrascript/commit/0019821dd411d3aa89d5c988c6add68f7ce9a36b
