### ISSUE TITLE
Terraform 0.12 compatibility

### ISSUE THREAD

**Issue by jbscare** [starhawking/python-terrascript#62]
It'd be great if Terrascript were compatible with Terraform 0.12 when it came out (or soon after).

**Comment by mjuenema** [comment]
Hi Josh, 

I fear that's going to be quite a challenge. I haven't really looked into it yet but one option would be to create a completely new Terrascript2 project for Terraform 0.12+. It appears that Hashicorp cleaned up some oddities of the JSON configuration language for Terraform 11 and earlier. That may make my job actually much easier. Maintaining backwards compatibility might become a complete nightmare. So the current Terrascript release may be "frozen" and future development may go into "Terrascript2".

Markus

PS: I am contemplating asking the community whether anyone is interested in becoming co-maintainer(s) of the project. I only have limited time available and could do with some help.

-- 
 Markus Juenemann
 markus@juenemann.net

**Comment by nielsonsantana** [comment]
@mjuenema, I think that I would be a co-maintener. I'm currently building the script to create the resources/data based on documentation (https://github.com/terraform-providers/).

**Comment by mjuenema** [comment]
Thanks Nielson, I am going to check how that works on Github. I'll let you know.

Markus

-- 
 Markus Juenemann
 markus@juenemann.net

**Comment by Spikeophant** [comment]
I'd happily jump in and help with this work, I am starting to use this at work, and they would let me work on this on the clock.  I'm also going to go through other issues and see if I can help.

**Comment by mjuenema** [comment]
@Spikeophant Great thanks.

**Comment by mjuenema** [comment]
I am going to start on a separate branch for Terraform 0.12 soon.

**Comment by somehowadev** [comment]
Hey, how's this going? Need any help?

**Comment by mjuenema** [comment]
Sorry for the lack of progress here. First I have been really busy with work and now I am away on holidays (much nicer!). I hope that I can start on Terraform 0.12 compatibility sometime in early August.

**Comment by Spikeophant** [comment]
I'm in the same boat, swamped with work, we pushed back our TF 0.12 project until August as well so this aligns with the timeline I'll be able to jump in too.

**Comment by mjuenema** [comment]
There is now a ``develop-0.7`` branch which has not seen much testing yet but contains a lot of changes introduced by Pull Request #72. 
Personally I will be focussing on a major code rewrite which will eventually become release 0.8.0. I find the (my!) current code really messy and that's never a good sign.

**Comment by mjuenema** [comment]
I am closing this is as I am actively (really, just started finding some time!!!) working on 0.8.0 which will support Terraform 0.12
