### ISSUE TITLE
Enhancement request: Add support for 'OCI' provider 

### ISSUE THREAD

**Issue by wggit** [starhawking/python-terrascript#63]
It will be really valuable to add and support for OCI (Oracle Cloud Infrastructure). 

Thank you.

**Comment by mjuenema** [comment]
Hi wggit, do you think you are able to add the missing code and submit a pull request?

**Comment by mjuenema** [comment]
This has been added for the future 0.8.0 release but must still be back-ported into the ``develop-0.6`` and ``develop-0.7`` branches.

**Comment by mjuenema** [comment]
Not going to back-port this into develop-0.6 and develop-0.7 branches.
