### ISSUE TITLE
Release 0.6.1?

### ISSUE THREAD

**Issue by jbscare** [starhawking/python-terrascript#70]
Any thoughts about releasing a version 0.6.1? There's been a lot of stuff since 0.6.0. :^)

(Opening a ticket doesn't seem like the best way to suggest this, but I wasn't sure what else would be better.)

**Comment by mjuenema** [comment]
Opening a ticket is fine as it is easy to reference. I am currently overseas on holidays for another week. I can create a 0.6.1 release when I am back home.

**Comment by jbscare** [comment]
Awesome; thanks!

**Comment by mjuenema** [comment]
Following a suggestion by @nielsonsantana this will probably be 0.7.0 as there are quite a few changes.

**Comment by rosscdh** [comment]
? progress

**Comment by mjuenema** [comment]
Done - and thanks for everyone's patience.
Please check ``README.md`` and ``DEVELOPMENT.md`` in the ``develop`` branch for important information regarding current releases.
