### ISSUE TITLE
Terrascript-Google Cloud Platform

### ISSUE THREAD

**Issue by iamdaaniyaal** [starhawking/python-terrascript#77]
Does python-terrascript work for Google Cloud Platform?

**Comment by nielsonsantana** [comment]
Hi @iamdaaniyaal. Yes. Here the resources for Google Cloud Plataform.
https://github.com/mjuenema/python-terrascript/tree/develop/terrascript/google

**Comment by iamdaaniyaal** [comment]
Hi @nielsonsantana. Thanks for helping out with the GCP resource.
Is there some documentation / guide to use the GCP module of Terrascript as I am unable to understand its usage?

**Comment by mjuenema** [comment]
@iamdaaniyaal Is your question specific to Google Cloud Platform or how Terrascript works generally? Have you used Terrascript with other providers, for instance Amazon Web Services?

**Comment by mjuenema** [comment]
Hi @iamdaaniyaal, I will be closing this issue in the next few days for lack of activity.

**Comment by mjuenema** [comment]
Closed for lack of activity.
