### ISSUE TITLE
Start a Slack channel for Python-Terrascript(?)

### ISSUE THREAD

**Issue by mjuenema** [starhawking/python-terrascript#92]

**Comment by mjuenema** [comment]
Created Zulip organisation.

**Comment by mjuenema** [comment]
Test

**Comment by mjuenema** [comment]
Reopen

**Comment by mjuenema** [comment]
Close

**Comment by jbscare** [comment]
Is this for chatting with users, or just notifications from GitHub? If the former, where would users find it? :^ )

**Comment by mjuenema** [comment]
Wow, Josh, you are quicker than I am. It's meant to be a communications channel that's less formal than Github issues for example. One could chat about anything related to the project. It's not on Slack but on Zulip (https://python-terrascript.zulipchat.com/) where you can log in using your Github account. I am going to put a link on the Python-Terrascript project page soon.

**Comment by jbscare** [comment]
Hiya! I tried to sign in there using my GitHub account, but it said that I needed an invitation. Is that as expected?

**Comment by mjuenema** [comment]
Hi Josh, no that's not how it is supposed to be. Let me check this.

**Comment by mjuenema** [comment]
Hi Josh, please try again. You should be able to join the "organization" without an invitation.

**Comment by jbscare** [comment]
It worked! Not a lot of users there. :^) Thanks!

**Comment by mjuenema** [comment]
True, it may be a dead end.
